CREATE DATABASE DOC_CONNECT;

CREATE TABLE LOGIN_DETAILS
(
USER_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
USER_NAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE PATIENT
(
PATIENT_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
USER_ID INT NOT NULL,
HEALTH_ISSUES VARCHAR(50),
ALLERGIES VARCHAR(50),
FOREIGN KEY (USER_ID) REFERENCES LOGIN_DETAILS(USER_ID)
);

CREATE TABLE USER_TABLE
(
USER_ID INT NOT NULL,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
CONTACT VARCHAR(20),
EMAIL VARCHAR(50) NOT NULL,
MARITAL_STATUS INT DEFAULT 0,
GENDER INT DEFAULT 0,
DOB VARCHAR(50) ,
ADDRESS VARCHAR(50),
POSTAL_CODE VARCHAR(10), 
CITY VARCHAR(20),
PROVINCE VARCHAR(20),
COUNTRY VARCHAR(20),
IS_ADMIN BIT DEFAULT 0,
IS_DOCTOR BIT DEFAULT 0,
FOREIGN KEY (USER_ID) REFERENCES LOGIN_DETAILS(USER_ID)
);

CREATE TABLE DOCTOR
(
DOCTOR_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
USER_ID INT NOT NULL,
DEGREE VARCHAR(50) ,
GRADUATED_FROM VARCHAR(50) ,
YEARS_OF_EXP INT DEFAULT 0,
FIELD_OF_PRACTICE VARCHAR(50) ,
IS_FULL_TIME BIT DEFAULT 0 ,
CURRENT_WORKING_STATUS VARCHAR(20) ,
DEPARTMENT VARCHAR(50) ,
DOJ VARCHAR(50) ,
AVAILABILITY VARCHAR(40) ,
IS_ACTIVE BIT DEFAULT 0,
FOREIGN KEY (USER_ID) REFERENCES LOGIN_DETAILS(USER_ID)
);

CREATE TABLE APPOINTMENTS
(
APPOINTMENT_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
PATIENT_ID INT NOT NULL,
DOCTOR_ID INT NOT NULL,
DURATION INT DEFAULT 0,
TITLE VARCHAR(100) NULL,
APPOINTMENT_DATE VARCHAR(50) NOT NULL,
DOCTOR_NOTES VARCHAR(100),
REMARKS VARCHAR(100),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
);

CREATE TABLE GENDER
(
GENDER_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
DESCRIPTION VARCHAR(50) NOT NULL,
);

CREATE TABLE MARITAL_STATUS
(
STATUS_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
DESCRIPTION VARCHAR(50) NOT NULL,
);

INSERT INTO GENDER(DESCRIPTION) VALUES ('Woman')
INSERT INTO GENDER(DESCRIPTION) VALUES ('Man')
INSERT INTO GENDER(DESCRIPTION) VALUES ('Transgender')
INSERT INTO GENDER(DESCRIPTION) VALUES ('Non-binary/non-conforming')
INSERT INTO GENDER(DESCRIPTION) VALUES ('Prefer not to respond')

INSERT INTO MARITAL_STATUS(DESCRIPTION) VALUES ('Single or never married')
INSERT INTO MARITAL_STATUS(DESCRIPTION) VALUES ('Married')
INSERT INTO MARITAL_STATUS(DESCRIPTION) VALUES ('Widowed and not remarried')
INSERT INTO MARITAL_STATUS(DESCRIPTION) VALUES ('Divorced and not remarried')
INSERT INTO MARITAL_STATUS(DESCRIPTION) VALUES ('Married but separated')
INSERT INTO MARITAL_STATUS(DESCRIPTION) VALUES ('Prefer not to respond')

INSERT INTO LOGIN_DETAILS(USER_NAME, PASSWORD) VALUES('pkandhari', 'pkandhari');
INSERT INTO USER_TABLE(USER_ID, FIRST_NAME, LAST_NAME, EMAIL, IS_ADMIN) VALUES (1,'Pritpal', 'Kandhari', 'p.p.singh92@gmail.com', 1)
